fn cycle_sort(a: int*, len: const usize) -> int {
    let writes = 0;
    for cs in 0..(len - 1) {
        let item = a[cs];
        let pos = cs;
        for i in (cs + 1)..len {
            if a[i] < item { pos++; }
        }
        if pos != cs {
            while item == a[pos] { pos++; }
            let t = a[pos];
            a[pos] = item;
            item = t;
            while pos != cs {
                pos = cs;
                for i in (cs + 1)..len {
                    if a[i] < item { pos++; }
                }
                while item == a[pos] { pos++; }
                let u = a[pos];
                a[pos] = item;
                item = u;
                writes++;
            }
        }
    }
    return writes;
}

fn main() {
    let a1 = [4, 65, 2, -31, 0, 99, 2, 83, 782, 1];
    let a2 = [7, 5, 2, 6, 1, 4, 2, 6, 3];
    let aa: int*[2] = [a1, a2];
    let lens = [a1.len, a2.len];
    for i in 0..aa.len {
        print "Before: [";
        for j in 0..lens[i] { print "{aa[i][j]}, "; }
        println "\b\b]";
        let w = cycle_sort(aa[i], lens[i]);
        print "After : [";
        for j in 0..lens[i] { print "{aa[i][j]}, "; }
        println "\b\b] ";
        println "Writes : {w}\n";
    }
}

const std = @import("std");

pub fn main(init: std.process.Init) !void {
    const io: std.Io = init.io;
    var stdouter_buf: [512]u8 = undefined;
    var stdouter = std.Io.File.stdout().writer(io, &stdouter_buf);

    var array = [_]i32{ 1, 4, 65, 2, -31, 0, 99, 2, 83, 782, 1 };
    for (0..array.len) |i| try stdouter.interface.print("{d},", .{array[i]});
    try stdouter.interface.print("\n", .{});
    cyclesort(&array);
    for (0..array.len) |i| try stdouter.interface.print("{d},", .{array[i]});
    try stdouter.flush();
}

fn cyclesort(arr: []i32) void {
    for (0..arr.len - 1) |start| {
        var j: i32 = arr[start];
        var first: bool = true;
        while (true) {
            var count: usize = start;
            var tmp: i32 = undefined;
            for (start + 1..arr.len) |k| {
                count += if (j > arr[k]) 1 else 0;
            }
            if (first and count == start) break;
            while (j == arr[count] and count + 1 < arr.len) count += 1;
            tmp = arr[count];
            arr[count] = j;
            j = tmp;
            if (count == start) break;
            first = false;
        }
    }
}
