import "std/string.zc"

fn split(s: String) {
    if s.length() == 0 { return; }
    let last = s.utf8_get(0);
    let curr = String::from_rune(last);
    for i, code in s {
        if i != 0 {
            if code == last {
                let c = String::from_rune(code);
                curr += &c;
            } else {
                print "{curr}, ";
                curr = String::from_rune(code);
            }
            last = code;
        }
    }
    println "{curr}";
}

fn main() {
    let s = String::from("gHHH5YY++///\\");
    split(s);
}
