import "std/string.zc"

fn split(s: String) {
    if s.length() == 0 { return; }
    let last = s.utf8_at(0);
    let curr = last;
    for i, code in s {
        if i != 0 {
            let c = String::from_rune(code);
            if c == last {
                curr += &c;
            } else {
                print "{curr}, ";
                curr = c;
            }
            last = c;
        }
    }
    println "{curr}";
}

fn main() {
    let s = String::from("gHHH5YY++///\\");
    split(s);
}
