
fn main() {
    comptime {
        let N = 20;
        let fib: long[20];
        fib[0] = (long)0;
        fib[1] = (long)1;
        for let i=2; i<N; i+=1 {
            fib[i] = fib[i-1] + fib[i-2];
        }

        code("let fibs: int[");
        code(N);
        code("] = [");
        for let i=0; i<N; i+=1 {
            code(fib[i]);
            if (i < N-1) code(", ");
        }
        code("];\n");
    }

    print "Compile-time generated Fibonacci sequence:\n";
    for i in 0..20 {
        print f"fib[{i}] = {fibs[i]}\n";
    }
}
